"""Evaluate or fine-tune the Random Walk GNN on saved XY BLT splits.

This script intentionally avoids on-the-fly simulation: it expects the NPZ
artifacts generated by ``XYModel/generate_blt_dataset.py`` (``train.npz``,
``val.npz``, ``test.npz`` plus ``metadata.json``). It can optionally run a
few fine-tuning epochs before reporting metrics and Tc interval previews.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import torch
from torch.optim import Adam
from torch_geometric.loader import DataLoader

from RWGNN.data import SplitData, load_xy_splits
from RWGNN.model import RandomWalkGNN
from RWGNN.train import evaluate, train_epoch


def _make_loaders(splits: SplitData, batch_size: int) -> Tuple[DataLoader, DataLoader, DataLoader]:
    return (
        DataLoader(splits.train, batch_size=batch_size, shuffle=True),
        DataLoader(splits.val, batch_size=batch_size),
        DataLoader(splits.test, batch_size=batch_size),
    )


def _load_model(checkpoint: Path, in_channels: int, hidden_channels: int, device: torch.device) -> RandomWalkGNN:
    model = RandomWalkGNN(in_channels=in_channels, hidden_channels=hidden_channels).to(device)

    if not checkpoint.exists():
        print(f"Checkpoint {checkpoint} not found. Starting from random initialization.")
        return model

    payload = torch.load(checkpoint, map_location=device)
    saved_in_channels = payload.get("in_channels")
    state_dict = payload.get("model_state", payload)

    if saved_in_channels is not None and saved_in_channels != in_channels:
        print(
            f"Warning: checkpoint was trained with in_channels={saved_in_channels}, "
            f"but current data uses in_channels={in_channels}. The first GCN layer will "
            "be reinitialized while other compatible weights are loaded."
        )

    expected = model.state_dict()
    filtered_state = {}
    dropped_keys = []
    for key, tensor in state_dict.items():
        if key in expected and tensor.shape == expected[key].shape:
            filtered_state[key] = tensor
        else:
            dropped_keys.append(key)

    missing, unexpected = model.load_state_dict(filtered_state, strict=False)

    print(f"Loaded weights from {checkpoint}")
    if dropped_keys:
        print(f"Skipped incompatible parameters: {dropped_keys}")
    if missing:
        print(f"Missing parameters reinitialized: {missing}")
    if unexpected:
        print(f"Unexpected parameters ignored: {unexpected}")

    return model


def _optional_finetune(model: RandomWalkGNN, loaders: Tuple[DataLoader, DataLoader, DataLoader], device: torch.device, *, epochs: int, lr: float):
    if epochs <= 0:
        return
    optimizer = Adam(model.parameters(), lr=lr)
    train_loader, val_loader, _ = loaders
    for epoch in range(1, epochs + 1):
        train_loss = train_epoch(model, train_loader, optimizer, device)
        val_metrics = evaluate(model, val_loader, device)
        print(
            f"[finetune] epoch={epoch:02d} train_loss={train_loss:.4f} "
            f"val_acc={val_metrics.phase_acc:.3f} val_temp_mae={val_metrics.temp_mae:.3f} "
            f"val_tc_mae={val_metrics.tc_mae:.3f}"
        )


def _preview_predictions(model: RandomWalkGNN, loader: DataLoader, device: torch.device, *, max_batches: int = 1):
    model.eval()
    for batch_idx, batch in enumerate(loader):
        if batch_idx >= max_batches:
            break
        batch = batch.to(device)
        phase_probs, lower, upper, tc_mean = model.predict_with_interval(batch)
        preds = phase_probs.argmax(dim=-1)
        print("Sample predictions (phase | prob(ordered), prob(disordered) | Tc interval):")
        for i in range(min(5, batch.num_graphs)):
            print(
                f"  true={int(batch.y[i])} pred={int(preds[i])} "
                f"probs=({phase_probs[i,0].item():.3f}, {phase_probs[i,1].item():.3f}) "
                f"Tc={tc_mean[i].item():.3f} in [{lower[i].item():.3f}, {upper[i].item():.3f}]"
            )
        break


def main():
    parser = argparse.ArgumentParser(description="Inference helper for RWGNN using saved BLT splits")
    parser.add_argument("--dataset-dir", type=str, default="XYModel/blt_dataset", help="Directory with train/val/test NPZ splits.")
    parser.add_argument("--checkpoint", type=str, default="artifacts/rwg_nn.pt", help="Trained model checkpoint to load.")
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--hidden-channels", type=int, default=128)
    parser.add_argument("--walk-length", type=int, default=4)
    parser.add_argument("--num-walks", type=int, default=8)
    parser.add_argument("--finetune-epochs", type=int, default=0, help="Optional number of fine-tuning epochs before inference.")
    parser.add_argument("--lr", type=float, default=2e-3)
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir)
    checkpoint = Path(args.checkpoint)

    if not dataset_dir.exists():
        raise FileNotFoundError(f"Expected dataset directory at {dataset_dir}. Generate it with XYModel/generate_blt_dataset.py.")

    splits = load_xy_splits(dataset_dir, walk_length=args.walk_length, num_walks=args.num_walks)
    feature_size = splits.train[0].num_node_features

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    loaders = _make_loaders(splits, args.batch_size)

    model = _load_model(checkpoint, feature_size, args.hidden_channels, device)
    _optional_finetune(model, loaders, device, epochs=args.finetune_epochs, lr=args.lr)

    train_loader, val_loader, test_loader = loaders
    print("Evaluating on validation split...")
    val_metrics = evaluate(model, val_loader, device)
    print(
        f"val_acc={val_metrics.phase_acc:.3f} val_temp_mae={val_metrics.temp_mae:.3f} "
        f"val_tc_mae={val_metrics.tc_mae:.3f}"
    )

    print("Evaluating on test split...")
    test_metrics = evaluate(model, test_loader, device)
    print(
        f"test_acc={test_metrics.phase_acc:.3f} test_temp_mae={test_metrics.temp_mae:.3f} "
        f"test_tc_mae={test_metrics.tc_mae:.3f}"
    )

    print("Previewing a few predictions from the test split...")
    _preview_predictions(model, test_loader, device)

    if args.finetune_epochs > 0:
        checkpoint.parent.mkdir(parents=True, exist_ok=True)
        torch.save({"model_state": model.state_dict(), "in_channels": feature_size}, checkpoint)
        print(f"Saved fine-tuned weights to {checkpoint}")


if __name__ == "__main__":
    main()
