"""Data utilities for the Random Walk GNN BLT experiments.

This module couples the existing XY model Metropolis sampler with PyTorch
Geometric-friendly datasets. It builds grid graphs with periodic boundary
conditions, decorates node features with random-walk positional encodings,
and exposes split loaders backed by the NPZ artefacts generated by
``XYModel/generate_blt_dataset.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Tuple

import json
import numpy as np
import torch
from torch import Tensor
from torch_geometric.data import Data


@dataclass
class SplitData:
    """Simple container for split-aware datasets."""

    train: List[Data]
    val: List[Data]
    test: List[Data]


def _build_periodic_grid_edges(lattice_shape: Tuple[int, int]) -> Tensor:
    """Return ``edge_index`` for a 2D periodic square lattice.

    The connectivity mirrors the XY simulator: each site connects to its
    four nearest neighbours with wrap-around at the boundaries.
    """

    rows, cols = lattice_shape
    edges: List[Tuple[int, int]] = []
    for r in range(rows):
        for c in range(cols):
            idx = r * cols + c
            right = r * cols + (c + 1) % cols
            left = r * cols + (c - 1) % cols
            down = ((r + 1) % rows) * cols + c
            up = ((r - 1) % rows) * cols + c
            for nbr in (right, left, down, up):
                edges.append((idx, nbr))
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    return edge_index


def _random_walk_pe(edge_index: Tensor, num_nodes: int, *, walk_length: int, num_walks: int) -> Tensor:
    """Compute simple random-walk positional encodings without extra dependencies.

    PyG exposes ``torch_geometric.utils.random_walk`` only when optional
    extensions are compiled. To avoid that requirement, we implement a small
    pure-PyTorch sampler that steps uniformly over the outgoing neighbors of
    each node. For every node, ``num_walks`` walks of length ``walk_length``
    are launched and we record the return probability after each step.
    """

    # Build adjacency lists once for cheap neighbor sampling.
    neighbors = [[] for _ in range(num_nodes)]
    for src, dst in edge_index.t().tolist():
        neighbors[src].append(dst)

    start_nodes = torch.arange(num_nodes).repeat_interleave(num_walks)
    walks = torch.zeros((start_nodes.numel(), walk_length + 1), dtype=torch.long)
    walks[:, 0] = start_nodes

    current = start_nodes.clone()
    for step in range(1, walk_length + 1):
        next_nodes = torch.empty_like(current)
        for idx, node in enumerate(current.tolist()):
            nbrs = neighbors[node] or [node]
            next_nodes[idx] = nbrs[torch.randint(len(nbrs), ())]
        walks[:, step] = next_nodes
        current = next_nodes

    rwpe = torch.zeros((num_nodes, walk_length), dtype=torch.float)
    for step in range(1, walk_length + 1):
        visits = walks[:, step] == start_nodes
        counts = torch.bincount(start_nodes, weights=visits.float(), minlength=num_nodes)
        rwpe[:, step - 1] = counts / float(num_walks)
    return rwpe


def lattice_vectors_to_data(
    lattice_vectors: np.ndarray,
    temperature: float,
    critical_temperature: float,
    *,
    lattice_shape: Tuple[int, int],
    edge_index: Tensor,
    walk_length: int = 4,
    num_walks: int = 8,
) -> Data:
    """Convert a lattice snapshot into a :class:`torch_geometric.data.Data` object."""

    num_nodes = lattice_shape[0] * lattice_shape[1]
    node_features = torch.tensor(lattice_vectors.reshape(num_nodes, -1), dtype=torch.float)
    rw_features = _random_walk_pe(edge_index, num_nodes, walk_length=walk_length, num_walks=num_walks)
    x = torch.cat([node_features, rw_features], dim=1)

    # Phase label: 0 for ordered (T < Tc), 1 for disordered (T >= Tc)
    phase_label = torch.tensor([int(temperature >= critical_temperature)], dtype=torch.long)
    temp_target = torch.tensor([temperature], dtype=torch.float)
    tc_target = torch.tensor([critical_temperature], dtype=torch.float)

    return Data(x=x, edge_index=edge_index, y=phase_label, temperature=temp_target, tc_target=tc_target)


def _load_npz_split(path: Path) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    payload = np.load(path)
    return payload["features"], payload["temperatures"], payload["labels"]


def load_xy_splits(
    data_dir: Path,
    *,
    walk_length: int = 4,
    num_walks: int = 8,
) -> SplitData:
    """Load NPZ splits produced by :mod:`XYModel.generate_blt_dataset` as PyG graphs."""

    meta = json.loads((data_dir / "metadata.json").read_text())
    lattice_shape = tuple(meta["lattice_shape"])
    critical_temperature: float = float(meta.get("critical_temp", 0.89))

    edge_index = _build_periodic_grid_edges(lattice_shape)

    def build_split(split_name: str) -> List[Data]:
        features, temps, _ = _load_npz_split(data_dir / f"{split_name}.npz")
        graphs: List[Data] = []
        for lattice, temp in zip(features, temps):
            lattice = np.asarray(lattice)
            expected_sites = lattice_shape[0] * lattice_shape[1]

            if lattice.size not in {expected_sites, expected_sites * 2}:
                raise ValueError(
                    "Unexpected lattice feature shape: "
                    f"got {lattice.shape} (size={lattice.size}), "
                    f"expected {expected_sites} or {expected_sites * 2}."
                )

            # Preserve the provided feature representation (angles or already
            # vectorised) without forcing a cosine/sine expansion.
            lattice_vectors = lattice.reshape(*lattice_shape, -1)

            graphs.append(
                lattice_vectors_to_data(
                    lattice_vectors,
                    float(temp),
                    critical_temperature,
                    lattice_shape=lattice_shape,
                    edge_index=edge_index,
                    walk_length=walk_length,
                    num_walks=num_walks,
                )
            )
        return graphs

    return SplitData(train=build_split("train"), val=build_split("val"), test=build_split("test"))


def generate_from_simulator(
    temperatures: Iterable[float],
    samples_per_temp: int,
    *,
    lattice_shape: Tuple[int, int],
    steps: int,
    iters_per_step: int,
    seed: int,
    coupling: float,
    walk_length: int = 4,
    num_walks: int = 8,
    critical_temperature: float = 0.89,
) -> List[Data]:
    """Generate lattices on the fly from the XY model and convert to PyG graphs."""

    from XYModel.xy import XYModelMetropolisSimulation  # Local import keeps optional dependency light

    rng = np.random.default_rng(seed)
    edge_index = _build_periodic_grid_edges(lattice_shape)
    graphs: List[Data] = []
    for temp in temperatures:
        beta = 1.0 / temp
        for _ in range(samples_per_temp):
            sim = XYModelMetropolisSimulation(
                lattice_shape=lattice_shape,
                beta=beta,
                J=coupling,
                random_state=int(rng.integers(0, 1_000_000_000)),
            )
            sim.simulate(steps=steps, iters_per_step=iters_per_step)
            # Keep the raw lattice angles instead of expanding to cosine/sine vectors
            lattice_vectors = np.asarray(sim.L, dtype=float)
            graphs.append(
                lattice_vectors_to_data(
                    lattice_vectors,
                    temp,
                    critical_temperature,
                    lattice_shape=lattice_shape,
                    edge_index=edge_index,
                    walk_length=walk_length,
                    num_walks=num_walks,
                )
            )
    return graphs

